[Feature/add-calendar-component] Adds Calendar to Dashboard
Usiel-03A7/eventoseve pull request #8
Opened 2023-11-01 08:03 UTC by AlanAnguiano

## Description

This Pull request adds the Calendar component to Dashboard component as well as some modifications in the sidebar in order to allow scrolling the content but not the sidebar

## Evidence

<img width="1440" alt="image" src="https://github.com/Usiel-03A7/eventoseve/assets/22619011/bed71df0-b408-4bf4-a47b-67df5b39f587">

## Link Issue (if applicable)
  -

2023-11-01 15:53 UTC, AlejandroCuriel requested changes
Please check the styles of your Calendar.css file and order the classes alphabetically ascending

2023-11-01 15:53 UTC, AlejandroCuriel commented on src/components/Dashboard/Calendar.css
> +  margin-top: 30px;
Sort this alphabetically

2023-11-01 15:53 UTC, AlejandroCuriel commented on src/components/Dashboard/Calendar.css
> +  display: flex;
Sort this alphabetically

2023-11-01 15:53 UTC, AlejandroCuriel commented on src/components/Dashboard/Calendar.css
> +  box-sizing: border-box;
Sort this alphabetically

2023-11-01 15:53 UTC, AlejandroCuriel commented on src/components/Dashboard/Calendar.css
> +  margin-bottom: 1em;
Sort this alphabetically

2023-11-01 15:53 UTC, AlejandroCuriel commented on src/components/Dashboard/Calendar.css
> +  align-items: center;
Sort this and the rest alphabetically please

2023-11-02 02:36 UTC, Usiel-03A7 approved these changes

2023-11-09 07:20 UTC, closed without merging